name: BlazorApp2
env:
  PUBLISH_DIR: bin/Release/netstandard2.1/publish/wwwroot

# Controls when the action will run
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Publish app
      run: dotnet publish -c Release

    - name: Rewrite base href
      uses: salimbhonhariya/ghaction-rewrite-base-href@v1
      with:
        html_path: ${{ env.PUBLISH_DIR }}/index.razor
        base_href: /BlazorApp2/

